// Generated by https://quicktype.io
export interface Card {
    id:           number;
    name:         string;
    last_numbers: string;
    verified:     boolean;
    active:       boolean;
}

export interface CardRequest {
    name:   string;
    number: string;
    month:  string;
    year:   string;
    cvc:    string;
}

export interface CardStatus {
    status: string;
    error:  string;
}

export interface CreateCardResponse {
    id:           number;
    name:         string;
    last_numbers: string;
    verified:     boolean;
    active:       boolean;
    errors: ErrorsFields;
}// Generated by https://quicktype.io

export interface CreateCardResponseError {
    message: string;
}


export interface ErrorsFields {
    month?:  string[];
    year?:   string[];
    name?:   string[];
    cvc?:    string[];
    number?: string[];
}

