// Generated by https://quicktype.io

export interface Card {
    id:           number;
    name:         string;
    last_numbers: string;
    verified:     boolean;
    active:       boolean;
}

// Generated by https://quicktype.io

export interface CardStatus {
    status: string;
    error: string;
}

