// Generated by https://quicktype.io
export interface Category {
    id:          number;
    name:        string;
    description: null | string;
    avatar:      null | string;
    count:       null;
    isExpanded: null | boolean
    categories:  Category[];
}
