// Generated by https://quicktype.io

import { SvgProps } from "react-native-svg";

export interface Category {
    id:          number;
    name:        string;
    description: null | string;
    avatar:      null | string;
    count:       null;
    categories:  Category[];
}
