// Generated by https://quicktype.io

export interface Products {
    data:  Product[];
    links: Links;
    meta:  Meta;
}

export interface Product {
    id:                  number;
    batch_id:            number;
    name:                string;
    description:         string;
    image:               string;
    images:              string[];
    brand:               Brand;
    sku:                 string;
    price:               string;
    price_with_discount: null | string;
    sale_price:          string;
    categories:          string[];
    stock:               number;
    branch:              Branch;
}

export interface Branch {
    id:                number;
    name:              string;
    logo:              string;
    banner:            string;
    description:       string;
    delivery_time:     string;
    created_at:        string;
    updated_at:        string;
    location:          Location;
    address:           string;
    phone:             string;
    schedule:          string;
    delivery_zone:     DeliveryZone[];
    allow_cash:        boolean;
    enable:            boolean;
    active:            boolean;
    min_amount:        string;
    distance_for_free: string;
    amount_for_free:   null;
}

export interface DeliveryZone {
    lat: number;
    lng: number;
}

export interface Location {
    type:        string;
    coordinates: number[];
}

export interface Brand {
    id:          number;
    name:        string;
    description: null;
    logo:        string;
}

export interface Links {
    first: string|null;
    last:  string|null;
    prev:  string|null;
    next:  string|null;
}

export interface Meta {
    current_page: number;
    from:         number;
    last_page:    number;
    links:        Link[];
    path:         string;
    per_page:     number;
    to:           number;
    total:        number;
}

export interface Link {
    url:    null | string;
    label:  string;
    active: boolean;
}
