// Generated by https://quicktype.io

export interface User {
    token: string;
    user:  UserProfile;
}

export interface UserProfile {
    id?:            number;
    name?:          string;
    avatar?:        string;
    email?:         string;
    created_at?:    string;
    phone?:         string;
    dui?:           string;
    nit?:           null;
    iva?:           string;
    occupation?:    Occupation;
    birthday?:      string;
    notifications?: boolean;
    bill_type?:     string;
    bill_entity?:   string;
}

export interface Occupation {
    id?:         number;
    name?:       string;
    created_at?: string;
    updated_at?: string;
}

export interface ErrorMessageLogin {
    error?: string;
}
